version: "3"
services:
  csvserver:
    image: csserver:latest 
    #build: .
    ports:
      - "9393:9300"
    volumes:
      - "./inputFile:/csvserver/inputdata"

    environment:
      - CSVSERVER_BORDER=Orange
 
